# Generated by Django 4.2.7 on 2023-11-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('phoneNo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('healthCondition', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('symptom', models.CharField(max_length=250)),
                ('cause', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('sideEffect', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateField(auto_now=True)),
                ('recordTime', models.TimeField(auto_now=True)),
                ('probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('disease_img', models.ImageField(upload_to='static/media/')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dermoral.disease')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dermoral.account')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dermoral.disease')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dermoral.medicine')),
            ],
        ),
    ]
