# Generated by Django 4.2.7 on 2023-11-13 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermoral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/media/')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='disease_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dermoral.image'),
        ),
    ]
