# Generated by Django 4.2.7 on 2023-11-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermoral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='sideEffect',
            field=models.TextField(max_length=500),
        ),
    ]
