# Generated by Django 4.2.7 on 2023-11-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dermoral', '0002_image_alter_record_disease_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='path',
        ),
    ]
